Get https://exercise-phonebook-backend-m.fly.dev/api/persons HTTP/1.1

###
GET https://exercise-phonebook-backend-m.fly.dev/api/persons/65bb280904b3c91ff2c635e4 HTTP/1.1
###
DELETE https://exercise-phonebook-backend-m.fly.dev/api/persons/id HTTP/1.1

###
POST https://exercise-phonebook-backend-m.fly.dev/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Arthur Pendragon",
    "number": "1212"
}

###
PUT https://exercise-phonebook-backend-m.fly.dev/api/persons/65c12da2f85b58afeba20fe2 HTTP/1.1
Content-Type: application/json

{
    "name": "Arthur Pendragon",
    "number": "1992"
}


###
PUT https://exercise-phonebook-backend-m.fly.dev/api/persons/65c12da2f85b58afeba20fe2 HTTP/1.1
Content-Type: application/json

{
    "name": "Arthur NotPendragon",
    "number": "192349222"
}

###
GET http://localhost:6786/api/persons/ HTTP/1.1

###
POST http://localhost:6786/api/persons HTTP/1.1

{
    "name": "Arthur Pendragon",
    "number": "1212"
}

###
DELETE http://localhost:6786/api/persons/2323 HTTP/1.1

###
PUT http://localhost:6786/api/persons/65c12da2f85b58afeba20fe2 HTTP/1.1
Content-Type: application/json

{
    "name": "Arthur Pendragon",
    "number": "1923492"
}

###
PUT http://localhost:6786/api/persons/65c12da2f85b58afeba20fe2 HTTP/1.1
Content-Type: application/json

{
    "name": "Arthur NotPendragon",
    "number": "192349222"
}