# fly.toml app configuration file generated for exercise-phonebook-backend-m on 2024-01-28T04:33:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exercise-phonebook-backend-m'
primary_region = 'waw'

[build]

[env]
  PORT = "6786" 

[http_service]
  internal_port = 6786
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
